// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.skysail.client.notes.roo;

import de.skysail.client.notes.roo.Note;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Note_Roo_Configurable {
    
    declare @type: Note: @Configurable;
    
}
